-- MySQL Script generated by MySQL Workbench
-- 10/24/19 08:17:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aso_campo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `aso_campo` ;

-- -----------------------------------------------------
-- Schema aso_campo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aso_campo` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `aso_campo` ;

-- -----------------------------------------------------
-- Table `aso_campo`.`tbladmin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aso_campo`.`tbladmin` ;

CREATE TABLE IF NOT EXISTS `aso_campo`.`tbladmin` (
  `identificacion` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL COMMENT '',
  `nombres` VARCHAR(70) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL COMMENT '',
  `apellidos` VARCHAR(70) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL COMMENT '',
  `telefono` VARCHAR(15) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL COMMENT '',
  `correo` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL COMMENT '',
  `contrasena` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL COMMENT '',
  `foto` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL COMMENT '',
  PRIMARY KEY (`identificacion`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

--
-- Volcado de datos para la tabla `tbladmin`
--

INSERT INTO `tbladmin` (`identificacion`, `nombres`, `apellidos`, `telefono`, `correo`, `contrasena`, `foto`) VALUES
('1007461282', 'Mariano', 'Sosa Uribe', '3135236926', 'marianososa325@gmail.com', '$2y$10$khbNn7necIAk7WnyBjBCSOolWL/c2q.mV3.JTYHDN/hz78ezD7UnK', '../foto/perfil/marian.png');

-- -----------------------------------------------------
-- Table `aso_campo`.`tbladmin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aso_campo`.`tblcliente` ;

CREATE TABLE IF NOT EXISTS `aso_campo`.`tblcliente` (
  `identificacion` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL COMMENT '',
  `nombres` VARCHAR(70) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL COMMENT '',
  `apellidos` VARCHAR(70) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL COMMENT '',
  `telefono` VARCHAR(15) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL COMMENT '',
  `correo` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL COMMENT '',
  `contrasena` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL COMMENT '',
  `foto` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL COMMENT '',
  PRIMARY KEY (`identificacion`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `aso_campo`.`tbltipo_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aso_campo`.`tbltipo_producto` ;

CREATE TABLE IF NOT EXISTS `aso_campo`.`tbltipo_producto` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`codigo`)  COMMENT '')
ENGINE = InnoDB;

--
-- Volcado de datos para la tabla `tbltipo_producto`
--

INSERT INTO `tbltipo_producto` (`codigo`, `nombre`) VALUES
(1, 'Verduras'),
(2, 'Frutas'),
(3, 'Productos de Granja');


-- -----------------------------------------------------
-- Table `aso_campo`.`tblproducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aso_campo`.`tblproducto` ;

CREATE TABLE IF NOT EXISTS `aso_campo`.`tblproducto` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL COMMENT '',
  `precio` DECIMAL(12,2) NOT NULL COMMENT '',
  `oferta` INT(5) NOT NULL COMMENT '',
  `tipo_producto` INT NOT NULL COMMENT '',
  `foto` VARCHAR(150) NULL COMMENT '',
  PRIMARY KEY (`codigo`)  COMMENT '',
  INDEX `fk_tblproducto_tipo_producto_idx` (`tipo_producto` ASC)  COMMENT '',
  CONSTRAINT `fk_tblproducto_tipo_producto`
    FOREIGN KEY (`tipo_producto`)
    REFERENCES `aso_campo`.`tbltipo_producto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

--
-- Volcado de datos para la tabla `tblproducto`
--

INSERT INTO `tblproducto` (`codigo`, `nombre`, `precio`, `oferta`, `tipo_producto`, `foto`) VALUES
(1, 'Brocoli', '1500.00', 0, 1, 'foto/brocoli.jpg'),
(2, 'Pimentón', '500.00', 0, 1, 'foto/pimenton.jpg'),
(3, 'Arveja', '2000.00', 0, 1, 'foto/arveja.jpg'),
(4, 'Lechuga', '800.00', 0, 1, 'foto/lechuga.jpg'),
(5, 'Zanahoria', '1200.00', 0, 1, 'foto/zanahorias.jpg'),
(6, 'Banano', '1700.00', 0, 2, 'foto/bananos.jpg'),
(7, 'Limón', '2300.00', 0, 2, 'foto/limones.jpg'),
(8, 'Mandarina', '800.00', 0, 2, 'foto/mandarinas.jpg'),
(9, 'Mora', '3500.00', 0, 2, 'foto/moras.jpg'),
(10, 'Naranja', '2500.00', 0, 2, 'foto/naranjas.jpg'),
(11, 'Miel', '8000.00', 0, 3, 'foto/miel.jpg'),
(12, 'Queso', '6000.00', 0, 3, 'foto/queso.jpg'),
(13, 'Huevos', '10800.00', 0, 3, 'foto/huevo.jpg'),
(14, 'Leche', '3000.00', 0, 3, 'foto/leche.jpg'),
(15, 'Yogurt', '3500.00', 0, 3, 'foto/yogurt.jpg');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
